apiVersion: v1
kind: ConfigMap
metadata:
  name: aks-scheduled-poolscaler-config
data:
  configuration.yml: |
    paramsDefs:
      few:
        enableAutoScaling: false
        count: 1
      normal:
        enableAutoScaling: false
        count: 2
      many:
        enableAutoScaling: true
        minCount: 2
        maxCount: 4
    resources:
      - resourceGroupName: "resourceGroupName"
        resourceName: "resourceName"
        agentPoolName: "agentPoolName"
        rules:
          - expr: "* * * * * Sun,Sat"
            paramsRef: few
          - expr: "* * 28-31 Dec * *"
            paramsRef: few
          - expr: "* * 1-3 Jan * *"
            paramsRef: few
          - expr: "* * 25 Dec * *"
            paramsRef: many
          - expr: "* * * * * *"
            paramsRef: normal
